name: CI

on:

  push:
    branches: [ master ]

jobs:

  ci_part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone my repo
        uses: actions/checkout@v2
           
      - name: Create Client Key nad Setup it
        run: set -eu && mkdir "$HOME/.ssh" && echo "${{ secrets.MY_HOST_SSH_KEY }}" > "$HOME/.ssh/key" && chmod 600 "$HOME/.ssh/key"
      
      - name: Deploy
        run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete -r . --exclude='.*' "${{ secrets.MY_HOST_NAME }}"@"${{ secrets.MY_HOST_IP }}":/var/www/ava-it.ru/html

      
